### ISSUE TITLE
Change word-splitting to let URLs be passed to #omit-word

### ISSUE THREAD

**Issue by sanchom** [mbutterick/hyphenate#5]
This is my code

```
(define capitalized? (λ(word) (let ([letter (substring word 0 1)])
  (equal? letter (string-upcase letter)))))

(define (ligs? word)
    (ormap (λ(lig) (regexp-match lig word))
           '("ff" "fi" "fl" "ffi" "ffl")))

(define (url? word)
  (ormap (λ (ending) (string-suffix? word ending))
         '(".ca" ".com")))

; Custom hyphenation that doesn't break URLs.
(define (custom-hyphenation x)
  (hyphenate x
             #:omit-word (λ (x) (or (capitalized? x) (ligs? x) (url? x)))))
```

At the REPL:

```
> (custom-hyphenation "Hyphenate shouldn't put a hyphen in navcanada.ca.")
"Hyphenate shouldn't put a hy\u00ADphen in nav\u00ADcana\u00ADda.ca."
``` 

Can the word-splitting algorithm be changed to treat navcanada.ca as a single word instead of as two words?

**Comment by sanchom** [comment]
Alternatively, I can just build an exception list by sweeping through the text and looking for URLs.

**Comment by mbutterick** [comment]
That would work. You could also break the string into chunks and use `#:omit-string` rather than `#:omit-word`:

```racket
#lang racket
(require hyphenate)

(define capitalized? (λ(word) (let ([letter (substring word 0 1)])
                                (equal? letter (string-upcase letter)))))

(define (ligs? word)
  (ormap (λ(lig) (regexp-match lig word))
         '("ff" "fi" "fl" "ffi" "ffl")))

(define (url? word)
  (regexp-match #rx"\\.[ca|com]" word))

; Custom hyphenation that doesn't break URLs.
(define (custom-hyphenation x)
  (define h (λ (x) (hyphenate x #:omit-string (λ (x) (or (capitalized? x)
                                                         (ligs? x)
                                                         (url? x))))))
  (string-join (map h (string-split x " ")) " "))

(module+ test
  (require rackunit)
  (check-equal?
   (custom-hyphenation "Hyphenate shouldn't put a hyphen in navcanada.ca.")
   "Hyphenate shouldn't put a hy\u00ADphen in navcanada.ca."))
```

**Comment by mbutterick** [comment]
BTW what I do when I’m using Pollen is designate a special X-expression attribute that signals that hyphenation should be suppressed (for instance in [Beautiful Racket](https://beautifulracket.com) it’s ``hyphens="none"``). 

Then you have a choice. 

1. You can check for this attribute in the `#:txexpr-proc` function of `decode`, and only pass the element to `hyphenate` if the attribute is missing. 

2. Or you can pass everything to `hyphenate` (because `hyphenate` can take X-expressions as input) and use the `#:omit-txexpr` argument of `hyphenate` check for the attribute. Same result.

Then, within my other Pollen tag functions, I can insert this attribute whenever I want something to remain unhyphenated. 

Ultimately, this makes the process more semantic (i.e., based on what the thing is) and less reliant on discovering some fantastic regex (which is usually hopeless with URLs and email addresses)

**Comment by sanchom** [comment]
Thanks :) I was actually right in the middle of trying to do something similar: omit hyphenation in `'(span ((class "sidenote")) "Don't hyphenate this stuff.")` I like the `hyphens="none"` solution.

**Comment by mbutterick** [comment]
BTW probably obvious but this is entirely separate from the CSS property `hyphens: none`. Which is actually a third option. Note the difference in behavior: when you use a `hyphens="none"` attribute in Pollen (though you can call it whatever you want, even `foo="bar"`) you prevent the hyphens from being inserted at all. When you use the CSS `hyphens: none`, they are inserted but not displayed.

For URLs, preventing hyphens from being inserted is the better move. That way, the URL can be copied and pasted from the page.
